-- Migration: 001_create_alerts
-- Stores alerts generated by the alert-service when log events exceed thresholds.

CREATE TABLE IF NOT EXISTS alerts (
    id           TEXT        PRIMARY KEY,
    log_entry_id TEXT        NOT NULL,
    service_name TEXT        NOT NULL,
    level        TEXT        NOT NULL,
    message      TEXT        NOT NULL,
    trace_id     TEXT        DEFAULT '',
    triggered_at TIMESTAMPTZ NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_service      ON alerts (service_name);
CREATE INDEX IF NOT EXISTS idx_alerts_level        ON alerts (level);
CREATE INDEX IF NOT EXISTS idx_alerts_triggered_at ON alerts (triggered_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_log_entry_id ON alerts (log_entry_id);
