#!/usr/bin/env node
// Backend↔frontend parity gate (ROAD_TO_100 · F0.1).
//
// Enforces the "backend and frontend in sync" rule as a ratchet:
//   • Every backend route must be either consumed by the UI, listed in `uiNone`
//     (never needs a UI), or listed in `knownOrphans` (Wave-2 backlog, frozen).
//   • A NEW backend route with no UI and no registry entry → FAIL (drift in).
//   • A `knownOrphans` entry that is now consumed or gone → FAIL ("delist it") so
//     the backlog can only shrink.
//   • A frontend /api call that hits no backend route and no proxy upstream →
//     FAIL (typo / dead call).
//
// Also writes PARITY_REPORT.md. Usage:
//   node scripts/parity/check-parity.mjs           # check, exit 1 on drift
//   node scripts/parity/check-parity.mjs --report  # write report, exit 0 always

import { readFileSync, writeFileSync } from 'node:fs';
import { backendRoutes, frontendCalls, normalizePath } from './extract.mjs';

const REPORT_ONLY = process.argv.includes('--report');
const registry = JSON.parse(readFileSync(new URL('./registry.json', import.meta.url)));
const REPO = new URL('../../', import.meta.url).pathname;

const clean = (obj) => Object.fromEntries(Object.entries(obj).filter(([k]) => k !== '_doc'));
const uiNone = clean(registry.uiNone);
const proxyUpstreams = clean(registry.proxyUpstreams);
const knownOrphans = clean(registry.knownOrphans);

const be = backendRoutes(); // key "METHOD /path"
const fe = frontendCalls(); // key "/path"
const fePaths = new Set(fe.keys());

// Segment-wise match: equal segment count, and each pair is equal or a ':p'
// wildcard on either side. This makes a frontend dynamic segment (e.g. an
// `${action}` that is resolve|mute|reopen) match the backend's literal action
// segment, and an id `${id}` match a backend `{id}`.
function segMatch(a, b) {
  const sa = a.split('/');
  const sb = b.split('/');
  if (sa.length !== sb.length) return false;
  for (let i = 0; i < sa.length; i++) {
    if (sa[i] === ':p' || sb[i] === ':p') continue;
    if (sa[i] !== sb[i]) return false;
  }
  return true;
}

// A backend route is "consumed" if the frontend references its path (method-
// agnostic: the UI call site rarely encodes the verb in a way we can read).
function isConsumed(route) {
  for (const p of fePaths) {
    if (segMatch(p, route.path)) return true;
    if (p.startsWith(route.path + '/')) return true; // deeper call under a prefix route
  }
  return false;
}

function underPrefix(path, prefixes) {
  return Object.keys(prefixes).some((pre) => path === pre || path.startsWith(pre + '/') || path.startsWith(pre));
}

// Match a "METHOD /path" or bare "/path" registry key against a route.
function inRegistry(route, table) {
  if (table[`${route.method} ${route.path}`]) return true; // exact METHOD+path
  if (table[route.path]) return true; // bare path
  // prefix (uiNone/proxy list bare paths as prefixes)
  return Object.keys(table).some((k) => {
    const kp = k.includes(' ') ? k.split(' ')[1] : k;
    return route.path === kp || route.path.startsWith(kp + '/');
  });
}

// ── Classify every backend route ──────────────────────────────────────────────
const consumed = [];
const coveredUiNone = [];
const backlog = []; // known orphans, allowed
const newOrphans = []; // NOT allowed → fail

for (const route of be.values()) {
  if (isConsumed(route)) consumed.push(route);
  else if (inRegistry(route, uiNone)) coveredUiNone.push(route);
  else if (knownOrphans[`${route.method} ${route.path}`]) backlog.push(route);
  else newOrphans.push(route);
}

// ── Stale known-orphans: listed but now consumed or no longer registered ──────
const beKeys = new Set([...be.values()].map((r) => `${r.method} ${r.path}`));
const consumedKeys = new Set(consumed.map((r) => `${r.method} ${r.path}`));
const staleOrphans = Object.keys(knownOrphans).filter(
  (k) => !beKeys.has(k) || consumedKeys.has(k)
);

// ── Reverse orphans: frontend calls with no backend route / proxy upstream ────
const reverseOrphans = [];
for (const call of fe.values()) {
  const bePathHit = [...be.values()].some(
    (r) => segMatch(r.path, call.path) || call.path.startsWith(r.path + '/') || r.path.startsWith(call.path + '/')
  );
  if (bePathHit) continue;
  if (underPrefix(call.path, proxyUpstreams)) continue;
  if (registry.frontendExternal && clean(registry.frontendExternal)[call.path]) continue;
  reverseOrphans.push(call);
}

// ── Report ────────────────────────────────────────────────────────────────────
const pct = (n, d) => (d === 0 ? 100 : Math.round((n / d) * 100));
const needsUi = be.size - coveredUiNone.length; // routes that should be reachable from UI
const parityPct = pct(consumed.length, needsUi);

const lines = [];
lines.push('# Backend ↔ Frontend Parity Report');
lines.push('');
lines.push(`_Generated by \`scripts/parity/check-parity.mjs\` — do not edit by hand._`);
lines.push('');
lines.push('| Metric | Count |');
lines.push('| --- | ---: |');
lines.push(`| Backend routes total | ${be.size} |`);
lines.push(`| — consumed by UI | ${consumed.length} |`);
lines.push(`| — no-UI-by-design (\`uiNone\`) | ${coveredUiNone.length} |`);
lines.push(`| — known orphans (Wave-2 backlog) | ${backlog.length} |`);
lines.push(`| — **NEW orphans (must fix)** | ${newOrphans.length} |`);
lines.push(`| Frontend calls total | ${fe.size} |`);
lines.push(`| — reverse orphans (no backend) | ${reverseOrphans.length} |`);
lines.push(`| **UI parity** (consumed ÷ needs-UI) | **${parityPct}%** |`);
lines.push('');

if (newOrphans.length) {
  lines.push('## ❌ NEW orphans — backend route with no UI and no registry entry');
  lines.push('Add the UI, or (if truly UI-less) add to `uiNone`, or (if deferred) to `knownOrphans` with its feature.');
  lines.push('');
  for (const r of newOrphans.sort(cmp)) lines.push(`- \`${r.method} ${r.path}\` — ${r.file}`);
  lines.push('');
}
if (staleOrphans.length) {
  lines.push('## ❌ Stale `knownOrphans` — fixed or removed, but still listed');
  lines.push('Delete these from `registry.json` (the backlog may only shrink).');
  lines.push('');
  for (const k of staleOrphans.sort()) lines.push(`- \`${k}\``);
  lines.push('');
}
if (reverseOrphans.length) {
  lines.push('## ❌ Reverse orphans — frontend calls a path with no backend route');
  lines.push('Likely a typo or a dead call. Fix the path, or add to `frontendExternal`/`proxyUpstreams`.');
  lines.push('');
  for (const c of reverseOrphans.sort((a, b) => a.path.localeCompare(b.path)))
    lines.push(`- \`${c.path}\` — ${[...c.files].join(', ')}`);
  lines.push('');
}

lines.push('## 🟡 Known orphans (Wave-2 backlog — allowed, burn down)');
lines.push('Each is a real backend capability with no UI yet. Ship the UI, then delete its registry entry.');
lines.push('');
const byFeature = {};
for (const [k] of Object.entries(knownOrphans)) {
  const feat = knownOrphans[k].split(' ')[0];
  (byFeature[feat] ||= []).push(k);
}
for (const feat of Object.keys(byFeature).sort()) {
  lines.push(`- **${feat}** — ${knownOrphans[byFeature[feat][0]].slice(feat.length + 1)}`);
  for (const k of byFeature[feat].sort()) lines.push(`  - \`${k}\``);
}
lines.push('');
lines.push('## ✅ No-UI-by-design');
lines.push('');
for (const r of coveredUiNone.sort(cmp)) lines.push(`- \`${r.method} ${r.path}\``);
lines.push('');

writeFileSync(new URL('../../PARITY_REPORT.md', import.meta.url), lines.join('\n'));

function cmp(a, b) {
  return `${a.path} ${a.method}`.localeCompare(`${b.path} ${b.method}`);
}

// ── Verdict ───────────────────────────────────────────────────────────────────
const failures = [];
if (newOrphans.length) failures.push(`${newOrphans.length} new backend route(s) with no UI`);
if (staleOrphans.length) failures.push(`${staleOrphans.length} stale knownOrphans entry(ies)`);
if (reverseOrphans.length) failures.push(`${reverseOrphans.length} frontend call(s) with no backend route`);

console.log(`Parity: ${parityPct}% UI coverage · ${consumed.length}/${needsUi} routes consumed · ${backlog.length} known orphans · report → PARITY_REPORT.md`);

if (failures.length && !REPORT_ONLY) {
  console.error('\n❌ PARITY GATE FAILED:');
  for (const f of failures) console.error(`   • ${f}`);
  console.error('   See PARITY_REPORT.md for details.');
  process.exit(1);
}
console.log(REPORT_ONLY ? '(report-only mode; not failing)' : '✅ parity gate passed');
