package sqlq

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// The sqlq counterpart of handler's TestNoRawTenantTableReads.
//
// That gate works by forbidding `.query(` in favour of `.queryScoped(`, which
// does not transfer here: sqlq talks to ClickHouse over its own HTTP client and
// to Postgres through database/sql, so there is no shared choke point to guard.
// The property to enforce is the same one though — no physical tenant-scoped
// table may be read without a tenant predicate — so it is enforced against the
// thing sqlq actually has: the physical mapping tables, and the source that
// might bypass them.

// physicalTenantTables are the stores' real tables holding per-tenant rows.
// Kept as a literal list, deliberately duplicated from the handler package's
// tenantScopedCHTables: a shared constant would let one edit silently relax two
// guards at once.
var physicalTenantTables = []string{
	"otel_traces", "otel_logs", "otel_metrics", "rum_events", "synthetic_results",
	"deployments", "incidents",
}

// Every mapping that names a physical table must carry a tenant predicate.
//
// Exhaustive over the mapping tables rather than over a list of relation names,
// so a relation added later is covered without anyone remembering to add it
// here.
func TestEveryPhysicalMappingIsTenantScoped(t *testing.T) {
	for name, tbl := range chTables {
		if strings.TrimSpace(tbl.tenantPred) == "" {
			t.Errorf("clickhouse mapping %q (%s) has no tenant predicate", name, tbl.table)
			continue
		}
		if !strings.Contains(tbl.tenantPred, "{tenant:String}") {
			t.Errorf("clickhouse mapping %q binds no tenant parameter: %q", name, tbl.tenantPred)
		}
	}
	// Postgres statements are generated by a single function; assert the clause
	// is there for every mapped relation rather than trusting the template.
	cat := DefaultCatalog()
	for name := range pgTables {
		rel, _ := cat.Lookup("", name)
		stmt, err := (&PostgresScanner{Rel: rel}).statement()
		if err != nil {
			t.Errorf("postgres mapping %q: %v", name, err)
			continue
		}
		if !strings.Contains(stmt, "WHERE tenant_id = $1") {
			t.Errorf("postgres mapping %q is not tenant-scoped: %s", name, stmt)
		}
	}
}

// No source file in this package may name a physical tenant-scoped table
// outside the mapping tables that are guarded above.
//
// This is the part that catches the future mistake: someone adding a convenience
// query — a count, a schema probe, a "just this once" lookup — that reads a real
// table directly and never passes through a Scanner. The mapping files are
// exempt because they are what the test above checks.
func TestNoPhysicalTableIsNamedOutsideTheGuardedMappings(t *testing.T) {
	exempt := map[string]bool{
		"scan_clickhouse.go": true, // the guarded ClickHouse mapping
		"scan_postgres.go":   true, // the guarded Postgres mapping
	}

	files, err := filepath.Glob("*.go")
	if err != nil {
		t.Fatalf("glob: %v", err)
	}

	var violations []string
	for _, f := range files {
		if strings.HasSuffix(f, "_test.go") || exempt[f] {
			continue
		}
		src, err := os.ReadFile(f)
		if err != nil {
			t.Fatalf("read %s: %v", f, err)
		}
		text := string(src)
		for _, tbl := range physicalTenantTables {
			// Word boundaries so the catalog's logical `incidents`/`deployments`
			// relation names — which are the same words — are only flagged when
			// they appear as a qualified physical reference or inside SQL.
			re := regexp.MustCompile(`(pulsetrace\.` + tbl + `\b)|(\bFROM\s+` + tbl + `\b)`)
			for _, m := range re.FindAllString(stripComments(text), -1) {
				violations = append(violations,
					f+": names physical table via "+strings.TrimSpace(m)+" outside a guarded mapping")
			}
		}
	}
	if len(violations) > 0 {
		t.Errorf("physical tenant tables must only be reached through a guarded scanner mapping:\n  %s",
			strings.Join(violations, "\n  "))
	}
}

// stripComments removes // and /* */ comments so prose describing the schema —
// of which this package has a lot, deliberately — cannot trip the guard.
func stripComments(src string) string {
	var b strings.Builder
	for i := 0; i < len(src); i++ {
		if i+1 < len(src) && src[i] == '/' && src[i+1] == '/' {
			for i < len(src) && src[i] != '\n' {
				i++
			}
			b.WriteByte('\n')
			continue
		}
		if i+1 < len(src) && src[i] == '/' && src[i+1] == '*' {
			i += 2
			for i+1 < len(src) && !(src[i] == '*' && src[i+1] == '/') {
				i++
			}
			i++
			continue
		}
		b.WriteByte(src[i])
	}
	return b.String()
}
