apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsetrace-config
  labels:
    {{- include "pulsetrace.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
